### ISSUE TITLE
**suggestion:** Consider adding error handling and rollback mechanisms

### ISSUE THREAD

**Issue by bartczak-pa** [bartczak-pa/WebScraper#69]
**suggestion:** Consider adding error handling and rollback mechanisms

The current workflow doesn't have any error handling or rollback mechanisms. Consider adding steps to check if the deployment was successful and implement a rollback strategy in case of failures. This will help maintain system stability during deployments.

```
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: |
          ./deploy-script.sh
      - name: Verify Deployment
        run: |
          ./verify-deployment.sh
      - name: Rollback on Failure
        if: failure()
        run: |
          ./rollback-script.sh
```

_Originally posted by @sourcery-ai[bot] in https://github.com/bartczak-pa/WebScraper/pull/67#discussion_r1752563008_
